(setq c-basic-offset 4)
(when (>= emacs-major-version 24)
    (require 'package)
    (add-to-list 'package-archives '("melpa" . "http://melpa.milkbox.net/packages/") t)
    (add-to-list 'package-archives '("org" . "http://orgmode.org/elpa/") t)
    (package-initialize)
)

(menu-bar-mode -1)
(tool-bar-mode -1)
(setq inhibit-startup-screen t)
